// ─────────────────────────────────────────────────────────────────────────────
// step_conditions — the §12.2 TRIG CONDITION truth table (ARCHITECTURE §5.1 L2,
// §12.2; user decisions D5/D6/D7; engine/sequencer/StepLogic.{h,cpp}).
//
// ── WHAT THIS FILE IS FOR, AND WHAT IT DELIBERATELY IS NOT ──────────────────
// It is NOT a golden. Goldens freeze bytes; this freezes the SEMANTICS the bytes
// are baked from — "3:4 fires on loop 3 of every 4", "1ST means loop index 0 and
// loop -1 is not it", "PRE means the previous GATED step actually sounded". A
// golden that encodes a wrong semantic is a permanently wrong reference, so the
// truth table has to exist first and separately, and it has to be written from
// §12.2 rather than from the implementation.
//
// ── THE THREE THINGS THAT ARE INDEPENDENTLY RE-WRITTEN HERE ─────────────────
// A test that computes its expectation by calling the function under test is
// vacuous. So three pieces are typed out longhand in this file and never sourced
// from the engine:
//
//   1. THE 30 (A, B) PAIRS, as 30 literal rows. `StepLogic.h` DERIVES them
//      arithmetically from the ordinal (four families, cumulative offsets
//      {0, 2, 6, 14}) and checks the derivation against the enum layout with a
//      `static_assert`. That check is real, but it proves "the decode agrees with
//      the enum's declaration ORDER" — both halves would move together if the
//      family boundaries were ever re-imagined. The literal table is the outside
//      witness: it says 1:16 is ordinal 15 and 8:8 is ordinal 14, in figures.
//   2. FLOOR-MOD, written as `((a % b) + b) % b` — a different expression from
//      `stepFloorMod`'s `r < 0 ? r + b : r`, so the two cannot share a mistake.
//   3. THE EXPECTED VERDICT of every one of the 39 conditions, as a switch over
//      the ordinal (`expectedCondition`).
//
// ── WHY MOST CASES DRIVE `conditionPasses` DIRECTLY ─────────────────────────
// Rather than through a render. A condition's whole job is to answer a yes/no
// about a step, and rendering wraps that answer in the transport, the pool, the
// note table and the block carving — four other things that can be wrong. The
// render-level checks belong to the goldens (`cond-a-b-8loops`, `cond-pre-chain`,
// Phase 7.3). Here the unit under test is the function, called at the index.
//
// ── THE FIXTURE'S ONE SUBTLETY: `pre` / `!pre` IN THE TRUTH TABLE ───────────
// The truth-table fixture sets the COND lane's length to 1, so EVERY step of the
// cycle carries the condition under test. For `pre`/`!pre` that is the
// non-well-founded case D6's depth budget exists to make total: no step in the
// gate cycle anchors the recurrence, so the backward walk exhausts its budget and
// takes the base case `false`. Both therefore read `false` there — `!pre` because
// the eight recorded links invert `false` an even number of times. That is a real
// row of the table, not a gap, and the dedicated PRE sections below cover the
// anchored cases the truth table cannot express.
// ─────────────────────────────────────────────────────────────────────────────

#include "engine/sequencer/PatternSnapshot.h"
#include "engine/sequencer/PatternTypes.h"
#include "engine/sequencer/StepLogic.h"

#include <catch2/catch_test_macros.hpp>

#include <cstddef>
#include <cstdint>
#include <iterator>
#include <memory>
#include <set>
#include <string>
#include <vector>

using arpbox::engine::abCycleFor;
using arpbox::engine::buildPatternSnapshot;
using arpbox::engine::conditionPasses;
using arpbox::engine::LaneId;
using arpbox::engine::laneDefault;
using arpbox::engine::laneOf;
using arpbox::engine::LaneState;
using arpbox::engine::maxPreChainDepth;
using arpbox::engine::maxSteps;
using arpbox::engine::neighbourModThreshold;
using arpbox::engine::numLanes;
using arpbox::engine::numTrigConditions;
using arpbox::engine::PatternData;
using arpbox::engine::PatternSetState;
using arpbox::engine::PatternSnapshot;
using arpbox::engine::StepRuntime;
using arpbox::engine::TrigCondition;

namespace
{
// ─────────────────────────────────────────────────────────────────────────────
// The independently written half
// ─────────────────────────────────────────────────────────────────────────────

/** Floor-modulus, written as `((a % b) + b) % b` — DELIBERATELY a different
    expression from `stepFloorMod`'s `r < 0 ? r + b : r`, so a mistake in one
    cannot be mirrored by the other. */
std::int64_t independentFloorMod (std::int64_t a, std::int64_t b) noexcept
{
    return ((a % b) + b) % b;
}

/** One `A:B` ordinal and the pair it MUST decode to. */
struct AbLiteral
{
    int ordinal;
    int a;
    int b;
};

/** THE 30 A:B ORDINALS, IN FIGURES. Not derived, not generated by a loop — typed
    out, because this table's entire value is that it was written from §12.2's
    enumeration (B ∈ {2, 4, 8, 16}, A running 1..B) by a different route than
    `abCycleFor`'s arithmetic. If the two ever disagree, one of them is a bug and
    the reader can see which by eye. */
constexpr AbLiteral abLiterals[30] = {
    { 1, 1, 2 },    { 2, 2, 2 },

    { 3, 1, 4 },    { 4, 2, 4 },    { 5, 3, 4 },    { 6, 4, 4 },

    { 7, 1, 8 },    { 8, 2, 8 },    { 9, 3, 8 },    { 10, 4, 8 },   { 11, 5, 8 },   { 12, 6, 8 },
    { 13, 7, 8 },   { 14, 8, 8 },

    { 15, 1, 16 },  { 16, 2, 16 },  { 17, 3, 16 },  { 18, 4, 16 },  { 19, 5, 16 },  { 20, 6, 16 },
    { 21, 7, 16 },  { 22, 8, 16 },  { 23, 9, 16 },  { 24, 10, 16 }, { 25, 11, 16 }, { 26, 12, 16 },
    { 27, 13, 16 }, { 28, 14, 16 }, { 29, 15, 16 }, { 30, 16, 16 },
};

/** The named-condition ordinals, pinned as literals here as well as by the
    `static_assert`s in PatternTypes.h — this file indexes the truth table by raw
    ordinal, so it needs to say out loud which ordinal it believes is which. */
constexpr int ordinalNone = 0;
constexpr int ordinalFirst = 31;
constexpr int ordinalNotFirst = 32;
constexpr int ordinalFill = 33;
constexpr int ordinalNotFill = 34;
constexpr int ordinalPre = 35;
constexpr int ordinalNotPre = 36;
constexpr int ordinalNei = 37;
constexpr int ordinalNotNei = 38;

/** THE EXPECTED VERDICT for condition `ordinal` at a step in pattern loop `loop`,
    with MOD A reading `modA` and the FILL pad `fill`.

    Written from §12.2 and the three user decisions, not from `StepLogic.cpp`.

    The `pre` / `notPre` rows are the UNANCHORED case only — see the header note.
    The truth-table fixture gives every step of the cycle the same condition, so a
    `pre` chain there has no anchor, exhausts D6's depth budget and takes the base
    case `false`; `notPre` inverts that base case once per recorded link, and the
    budget records exactly `maxPreChainDepth` (an even number) of them. */
bool expectedCondition (int ordinal, std::int64_t loop, int modA, bool fill) noexcept
{
    if (ordinal == ordinalNone)
        return true;

    for (const auto& row : abLiterals)
        if (row.ordinal == ordinal)
            return independentFloorMod (loop, row.b) == row.a - 1;

    switch (ordinal)
    {
    case ordinalFirst:
        return loop == 0;
    case ordinalNotFirst:
        return loop != 0;
    case ordinalFill:
        return fill;
    case ordinalNotFill:
        return ! fill;
    case ordinalPre:
        return false;
    case ordinalNotPre:
        return (maxPreChainDepth % 2) != 0;
    case ordinalNei:
        return modA >= 64;
    case ordinalNotNei:
        return modA < 64;
    default:
        break;
    }

    // Unreachable for 0..38; a new ordinal must be given a row above.
    return false;
}

// ─────────────────────────────────────────────────────────────────────────────
// Fixture construction
// ─────────────────────────────────────────────────────────────────────────────

/** Pattern 0 of a state whose lanes all sit at their §12.1 defaults, with the GATE
    lane explicitly filled (its default is 0 = silent, which would make every
    `previousGatedOffset` zero and every PRE section vacuous). */
PatternSetState defaultedState (int gateLength, int gateDivision, bool gateAllOn)
{
    PatternSetState state {};
    auto& pattern = state.patterns[0];

    for (int lane = 0; lane < numLanes; ++lane)
    {
        LaneState& target = pattern.lanes[static_cast<std::size_t> (lane)];
        target.length = 16;
        target.division = 1;

        for (int step = 0; step < maxSteps; ++step)
            target.values[static_cast<std::size_t> (step)] = laneDefault (static_cast<LaneId> (lane));
    }

    LaneState& gate = laneOf (pattern, LaneId::gate);
    gate.length = static_cast<std::uint8_t> (gateLength);
    gate.division = static_cast<std::uint8_t> (gateDivision);

    for (int step = 0; step < maxSteps; ++step)
        gate.values[static_cast<std::size_t> (step)] = gateAllOn ? 1 : 0;

    return state;
}

/** The truth-table fixture: GATE all-on over a 16-step cycle (so the pattern loop
    is 16 base steps and `loopIndexAt` is `floorDiv (step, 16)`), COND and MOD A
    lanes of LENGTH 1 so a single value covers every step of every loop. */
std::unique_ptr<const PatternSnapshot> truthTableSnapshot (int condOrdinal, int modAValue)
{
    PatternSetState state = defaultedState (16, 1, true);
    auto& pattern = state.patterns[0];

    LaneState& cond = laneOf (pattern, LaneId::cond);
    cond.length = 1;
    cond.values[0] = static_cast<std::int16_t> (condOrdinal);

    LaneState& modA = laneOf (pattern, LaneId::modA);
    modA.length = 1;
    modA.values[0] = static_cast<std::int16_t> (modAValue);

    return buildPatternSnapshot (state, 1);
}

/** The gate cycle used by the truth table, in base steps. Every loop-index
    expectation below is `floorDiv (stepIndex, this)`. */
constexpr std::int64_t truthTablePeriod = 16;

constexpr StepRuntime fillDown { true };
constexpr StepRuntime fillUp {};
} // namespace

// ─────────────────────────────────────────────────────────────────────────────
// A. The (A, B) decode — 30 ordinals against 30 literals
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE ("sequencer/step-conditions: every A:B ordinal decodes to its literal (a, b) pair", "[unit][determinism]")
{
    // THE GUARD AGAINST THE FAMILY BOUNDARIES DRIFTING. PatternTypes.h's
    // `static_assert`s pin the ORDINALS (`ab1of16` is 15, `ab16of16` is 30) and
    // StepLogic.h's `abDecodeIsExhaustive` pins that the decode agrees with the
    // enum's declaration order — but both of those are internal consistency. This
    // is the external witness: 30 pairs, in figures, from §12.2's enumeration.
    REQUIRE (static_cast<int> (std::size (abLiterals)) == 30);

    for (const auto& row : abLiterals)
    {
        const auto cond = static_cast<TrigCondition> (row.ordinal);
        const auto decoded = abCycleFor (cond);

        INFO ("ordinal " << row.ordinal << " expected " << row.a << ':' << row.b << " got " << decoded.a << ':'
                         << decoded.b);
        REQUIRE (decoded.a == row.a);
        REQUIRE (decoded.b == row.b);
    }

    // The block is exactly 30 long and nothing outside it decodes as an A:B cycle.
    REQUIRE (abCycleFor (TrigCondition::none).b == 0);

    for (int ordinal = ordinalFirst; ordinal < numTrigConditions; ++ordinal)
    {
        INFO ("named ordinal " << ordinal << " must not decode as A:B");
        REQUIRE (abCycleFor (static_cast<TrigCondition> (ordinal)).b == 0);
    }

    // The family boundaries, called out by name so a reader can check them without
    // scanning the table: :2 starts at 1, :4 at 3, :8 at 7, :16 at 15.
    REQUIRE (abCycleFor (TrigCondition::ab1of2).b == 2);
    REQUIRE (abCycleFor (TrigCondition::ab1of4).b == 4);
    REQUIRE (abCycleFor (TrigCondition::ab1of8).b == 8);
    REQUIRE (abCycleFor (TrigCondition::ab1of16).b == 16);
    REQUIRE (abCycleFor (TrigCondition::ab2of2).a == 2);
    REQUIRE (abCycleFor (TrigCondition::ab8of8).a == 8);
    REQUIRE (abCycleFor (TrigCondition::ab16of16).a == 16);
}

// ─────────────────────────────────────────────────────────────────────────────
// B. The full 39-entry truth table
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE ("sequencer/step-conditions: all 39 conditions match the hand-written truth table", "[unit][determinism]")
{
    // NO CATCH2 MACRO RUNS INSIDE THE SWEEP (the house convention — 39 x 15 x 4 x 2
    // x 2 assertions would be ~19k macro expansions and an undiagnosable failure
    // wall). Mismatches are counted and the first is described.
    //
    // The loop set spans NEGATIVE loops on purpose: `loopIndexAt` floor-divides, so
    // step -1 is loop -1 and step -17 is loop -2. Every A:B condition and 1ST/!1ST
    // is defined there, the retrigger lookahead and the locate paths reach there,
    // and `%` instead of `stepFloorMod` is invisible everywhere else.
    const std::int64_t loops[] = { -3, -2, -1, 0, 1, 2, 3, 4, 5, 6, 7, 8, 15, 16, 17 };
    const int modAValues[] = { 0, 63, 64, 127 };

    int checks = 0;
    int mismatches = 0;
    std::string firstMismatch;

    for (int ordinal = 0; ordinal < numTrigConditions; ++ordinal)
        for (const int modA : modAValues)
        {
            const auto snapshot = truthTableSnapshot (ordinal, modA);
            REQUIRE (snapshot != nullptr);
            const PatternData& data = snapshot->patterns[0];
            REQUIRE (data.gatePeriodSteps == truthTablePeriod);

            for (const std::int64_t loop : loops)
                // Two steps per loop — the loop's first base step and one in its
                // middle — so "the condition is a property of the LOOP, not of the
                // step" is asserted rather than assumed.
                for (const std::int64_t within : { std::int64_t { 0 }, std::int64_t { 5 } })
                    for (const bool fill : { false, true })
                    {
                        const std::int64_t step = loop * truthTablePeriod + within;
                        const StepRuntime runtime { fill };

                        const bool actual = conditionPasses (data, step, runtime);
                        const bool expected = expectedCondition (ordinal, loop, modA, fill);
                        ++checks;

                        if (actual != expected)
                        {
                            ++mismatches;

                            if (firstMismatch.empty ())
                                firstMismatch = "ordinal " + std::to_string (ordinal) + " loop " +
                                                std::to_string (loop) + " step " + std::to_string (step) + " modA " +
                                                std::to_string (modA) + " fill " + (fill ? "1" : "0") + " expected " +
                                                (expected ? "true" : "false") + " got " + (actual ? "true" : "false");
                        }
                    }
        }

    INFO ("checks " << checks << ", first mismatch: " << firstMismatch);
    REQUIRE (checks == numTrigConditions * 4 * 15 * 2 * 2);
    REQUIRE (mismatches == 0);
}

// ─────────────────────────────────────────────────────────────────────────────
// C. THE ACCEPTANCE CRITERION: "3:4 fires exactly on loop 3 of every 4"
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE ("sequencer/step-conditions: 3:4 fires on loop indices exactly {2, 6} across 8 loops", "[unit][determinism]")
{
    // INSTRUCTIONS Phase 7 success criterion, stated as a SET rather than a count.
    // A count of two is satisfied by {0, 4}, by {3, 7} — by any off-by-one in
    // either direction. §12.2 numbers loops from 1 and the engine indexes them from
    // 0, so "loop 3 of every 4" is loop INDEX 2, and dropping the `- 1` in
    // `stepFloorMod (loop, b) == a - 1` would fire on index 3 forever with nothing
    // else in the suite noticing.
    const auto snapshot = truthTableSnapshot (static_cast<int> (TrigCondition::ab3of4), 0);
    REQUIRE (snapshot != nullptr);
    const PatternData& data = snapshot->patterns[0];

    std::set<std::int64_t> firedLoops;

    for (std::int64_t loop = 0; loop < 8; ++loop)
        for (std::int64_t within = 0; within < truthTablePeriod; ++within)
            if (conditionPasses (data, loop * truthTablePeriod + within, fillUp))
                firedLoops.insert (loop);

    const std::set<std::int64_t> expected { 2, 6 };
    INFO ("fired on " << firedLoops.size () << " loops");
    REQUIRE (firedLoops == expected);

    // …and on EVERY step of those loops, not just their first — the condition gates
    // the loop, not the downbeat.
    for (std::int64_t within = 0; within < truthTablePeriod; ++within)
    {
        INFO ("loop 2 step offset " << within);
        REQUIRE (conditionPasses (data, 2 * truthTablePeriod + within, fillUp));
        REQUIRE (! conditionPasses (data, 3 * truthTablePeriod + within, fillUp));
    }

    // The three other members of the :4 family land on the three other loops, so
    // the family tiles the cycle exactly once. A decode that collapsed two
    // ordinals onto one loop would pass the 3:4 check above on its own.
    const int family[4] = { static_cast<int> (TrigCondition::ab1of4),
                            static_cast<int> (TrigCondition::ab2of4),
                            static_cast<int> (TrigCondition::ab3of4),
                            static_cast<int> (TrigCondition::ab4of4) };

    for (int member = 0; member < 4; ++member)
    {
        const auto memberSnapshot = truthTableSnapshot (family[member], 0);
        REQUIRE (memberSnapshot != nullptr);

        for (std::int64_t loop = 0; loop < 8; ++loop)
        {
            INFO ("family member " << member << " loop " << loop);
            REQUIRE (conditionPasses (memberSnapshot->patterns[0], loop * truthTablePeriod, fillUp) ==
                     (loop % 4 == member));
        }
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// D. 1ST / !1ST at negative indices
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE ("sequencer/step-conditions: 1ST is false at every negative index (loops -1, -2, ...)", "[unit][determinism]")
{
    // THE `<= 0` TYPO'S ONLY WITNESS. `loopIndexAt` floor-divides, so steps -1
    // through -16 are loop -1 and -17 through -32 are loop -2 — EARLIER loops, not
    // "the first loop". Writing `<= 0` instead of `== 0` is invisible during
    // ordinary forward playback (indices are non-negative there) and surfaces only
    // through the retrigger lookahead and the locate paths, i.e. as a note-LENGTH
    // bug that reads like a timing bug.
    //
    // Before this case, `tests/step_purity.cpp` swept indices from -37 but only ever
    // asserted SELF-CONSISTENCY (same index, same answer) — a uniformly wrong
    // verdict at negative indices is perfectly self-consistent. Nothing anywhere
    // asserted a condition's VALUE below zero.
    const auto firstSnapshot = truthTableSnapshot (ordinalFirst, 0);
    const auto notFirstSnapshot = truthTableSnapshot (ordinalNotFirst, 0);
    REQUIRE (firstSnapshot != nullptr);
    REQUIRE (notFirstSnapshot != nullptr);

    const PatternData& firstData = firstSnapshot->patterns[0];
    const PatternData& notFirstData = notFirstSnapshot->patterns[0];

    int negativeChecked = 0;

    for (std::int64_t step = -37; step <= -1; ++step)
    {
        INFO ("step " << step << " loop " << PatternSnapshot::loopIndexAt (firstData, step));
        REQUIRE (PatternSnapshot::loopIndexAt (firstData, step) < 0);
        REQUIRE (! conditionPasses (firstData, step, fillUp));
        REQUIRE (conditionPasses (notFirstData, step, fillUp));
        ++negativeChecked;
    }

    REQUIRE (negativeChecked == 37);

    // Loop 0 — the whole of it, and only it — is "first".
    for (std::int64_t step = 0; step < truthTablePeriod; ++step)
    {
        INFO ("loop-0 step " << step);
        REQUIRE (conditionPasses (firstData, step, fillUp));
        REQUIRE (! conditionPasses (notFirstData, step, fillUp));
    }

    for (std::int64_t step = truthTablePeriod; step < 3 * truthTablePeriod; ++step)
    {
        INFO ("later step " << step);
        REQUIRE (! conditionPasses (firstData, step, fillUp));
        REQUIRE (conditionPasses (notFirstData, step, fillUp));
    }
}

TEST_CASE ("sequencer/step-conditions: A:B uses floor-mod, so negative loops still tile the cycle",
           "[unit][determinism]")
{
    // C++ `%` yields NEGATIVE residues for negative operands, so `-1 % 4` is `-1`,
    // which equals `a - 1` for no A at all: with `%` in place of `stepFloorMod`
    // EVERY A:B condition silently fails for the whole of every negative loop. The
    // truth table above covers this too; this case states it as its own claim so a
    // failure names the cause.
    //
    // Loop -1 must be tiled by the :4 family exactly as loop 3 is:
    // floorMod (-1, 4) == 3, so 4:4 fires there.
    const int family[4] = { static_cast<int> (TrigCondition::ab1of4),
                            static_cast<int> (TrigCondition::ab2of4),
                            static_cast<int> (TrigCondition::ab3of4),
                            static_cast<int> (TrigCondition::ab4of4) };

    for (std::int64_t loop = -8; loop < 0; ++loop)
    {
        int firedHere = 0;

        for (int member = 0; member < 4; ++member)
        {
            const auto snapshot = truthTableSnapshot (family[member], 0);
            REQUIRE (snapshot != nullptr);

            const bool fired = conditionPasses (snapshot->patterns[0], loop * truthTablePeriod, fillUp);
            INFO ("negative loop " << loop << " member " << member);
            REQUIRE (fired == (independentFloorMod (loop, 4) == member));

            if (fired)
                ++firedHere;
        }

        // EXACTLY ONE member of the family fires per loop — the property `%` breaks
        // by making the count zero.
        INFO ("negative loop " << loop << " fired " << firedHere << " of 4");
        REQUIRE (firedHere == 1);
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// E. PRE / !PRE (user decision D6)
// ─────────────────────────────────────────────────────────────────────────────

namespace
{
/** A PRE-chain fixture: a 16-step all-on GATE cycle, an ANCHOR at step 0 whose
    condition is `anchorCond`, and `pre` (or `notPre`) on steps 1..15. */
std::unique_ptr<const PatternSnapshot> preChainSnapshot (TrigCondition anchorCond, TrigCondition chainCond)
{
    PatternSetState state = defaultedState (16, 1, true);
    auto& pattern = state.patterns[0];

    LaneState& cond = laneOf (pattern, LaneId::cond);
    cond.length = 16;
    cond.values[0] = static_cast<std::int16_t> (anchorCond);

    for (int step = 1; step < 16; ++step)
        cond.values[static_cast<std::size_t> (step)] = static_cast<std::int16_t> (chainCond);

    return buildPatternSnapshot (state, 1);
}
} // namespace

TEST_CASE ("sequencer/step-conditions: a PRE run propagates for 8 links and the 9th decays to silence",
           "[unit][determinism]")
{
    // D6 IN FULL: PRE refers to the previous GATED step, the chain is followed
    // `maxPreChainDepth` links deep, and the truncation base case is `false` —
    // "deep chains decay to silence", never to a self-sustaining note.
    //
    // WHY THE BOUNDARY IS THE INTERESTING INDEX. The backward walk records at most
    // `maxPreChainDepth` links; with an anchor at step 0 and `pre` on every step
    // after it, step k reaches the anchor iff k <= maxPreChainDepth. So step 8
    // (link 8) still resolves against the anchor and step 9 (link 9) does not — and
    // the two indices sit next to each other, which is the whole point of testing
    // here rather than at some comfortable depth.
    STATIC_REQUIRE (maxPreChainDepth == 8);

    const auto snapshot = preChainSnapshot (TrigCondition::none, TrigCondition::pre);
    REQUIRE (snapshot != nullptr);
    const PatternData& data = snapshot->patterns[0];

    // The anchor itself: `none`, PROB 100, so it sounds.
    REQUIRE (conditionPasses (data, 0, fillUp));

    for (std::int64_t link = 1; link <= maxPreChainDepth; ++link)
    {
        INFO ("link " << link << " (within budget) must inherit the anchor's `true`");
        REQUIRE (conditionPasses (data, link, fillUp));
    }

    // LINK 9 — one past the budget. The walk never reaches the anchor, takes D6's
    // base case `false`, and a run of `pre` links cannot resurrect it.
    INFO ("link 9 sits exactly on the truncation boundary");
    REQUIRE (! conditionPasses (data, maxPreChainDepth + 1, fillUp));

    // …and stays false for the rest of the run, so the decay is monotone rather
    // than an oscillation the boundary happened to catch at a `false` phase.
    for (std::int64_t link = maxPreChainDepth + 1; link < 16; ++link)
    {
        INFO ("link " << link << " (past budget)");
        REQUIRE (! conditionPasses (data, link, fillUp));
    }
}

TEST_CASE ("sequencer/step-conditions: PRE follows the previous GATED step, not the previous index",
           "[unit][determinism]")
{
    // §12.2 says "the previous step's result"; D6 reads that as the previous step
    // that could have SOUNDED. A rest is not a step that failed — it is not a step
    // at all, rhythmically — so the chain hops over it via `previousGatedOffset`.
    //
    // THE DISCRIMINATOR. GATE = [1, 0, 1, ...]: step 1 is a REST carrying `none`
    // (which passes), step 0 is the previous GATED step carrying `!1ST` (which
    // FAILS in loop 0). Step 2 carries `pre`. Following index k-1 would inherit
    // step 1's `true`; following the previous gated step inherits step 0's `false`.
    // The two readings therefore give opposite answers here.
    PatternSetState state = defaultedState (8, 1, false);
    auto& pattern = state.patterns[0];

    LaneState& gate = laneOf (pattern, LaneId::gate);
    const int gateValues[8] = { 1, 0, 1, 0, 0, 1, 0, 0 };
    for (int step = 0; step < 8; ++step)
        gate.values[static_cast<std::size_t> (step)] = static_cast<std::int16_t> (gateValues[step]);

    LaneState& cond = laneOf (pattern, LaneId::cond);
    cond.length = 8;
    cond.values[0] = static_cast<std::int16_t> (TrigCondition::notFirst); // anchor: FALSE in loop 0
    cond.values[1] = static_cast<std::int16_t> (TrigCondition::none);     // rest, would be TRUE
    cond.values[2] = static_cast<std::int16_t> (TrigCondition::pre);
    cond.values[3] = static_cast<std::int16_t> (TrigCondition::none);
    cond.values[4] = static_cast<std::int16_t> (TrigCondition::none);
    cond.values[5] = static_cast<std::int16_t> (TrigCondition::notPre);
    cond.values[6] = static_cast<std::int16_t> (TrigCondition::none);
    cond.values[7] = static_cast<std::int16_t> (TrigCondition::none);

    const auto snapshot = buildPatternSnapshot (state, 1);
    REQUIRE (snapshot != nullptr);
    const PatternData& data = snapshot->patterns[0];

    // The table itself: from phase 2 the previous gated phase is 0, two back.
    REQUIRE (data.gatePeriodSteps == 8);
    REQUIRE (PatternSnapshot::previousGatedOffsetAt (data, 2) == 2);
    REQUIRE (PatternSnapshot::previousGatedOffsetAt (data, 5) == 3);

    // Loop 0: the anchor's `!1ST` fails, so `pre` at step 2 fails and `!pre` at
    // step 5 (whose previous gated step is step 2) passes.
    REQUIRE (! conditionPasses (data, 0, fillUp));
    REQUIRE (! conditionPasses (data, 2, fillUp));
    REQUIRE (conditionPasses (data, 5, fillUp));

    // Loop 1: the anchor's `!1ST` now PASSES, and the chain flips with it — which
    // is what says the chain is genuinely re-derived from the anchor each time
    // rather than baked at build.
    REQUIRE (conditionPasses (data, 8, fillUp));
    REQUIRE (conditionPasses (data, 10, fillUp));
    REQUIRE (! conditionPasses (data, 13, fillUp));
}

TEST_CASE ("sequencer/step-conditions: the anchor's PROBABILITY counts toward the PRE chain", "[unit][determinism]")
{
    // D6's "result" means DID THAT STEP ACTUALLY SOUND, not "did its condition
    // pass". A PRE step downstream of a PROB-0 anchor must not fire: to the
    // listener the anchor was silent, so "the previous step played" is false.
    // Seeding the chain from the anchor's condition alone is the natural
    // simplification and it makes the chain disagree with what was heard.
    PatternSetState state = defaultedState (16, 1, true);
    auto& pattern = state.patterns[0];

    LaneState& cond = laneOf (pattern, LaneId::cond);
    cond.length = 16;
    cond.values[0] = static_cast<std::int16_t> (TrigCondition::none); // condition PASSES
    for (int step = 1; step < 16; ++step)
        cond.values[static_cast<std::size_t> (step)] = static_cast<std::int16_t> (TrigCondition::pre);

    LaneState& prob = laneOf (pattern, LaneId::prob);
    prob.length = 16;
    for (int step = 0; step < 16; ++step)
        prob.values[static_cast<std::size_t> (step)] = 100;
    prob.values[0] = 0; // …but the anchor never sounds

    const auto snapshot = buildPatternSnapshot (state, 1);
    REQUIRE (snapshot != nullptr);
    const PatternData& data = snapshot->patterns[0];

    // The anchor's own condition passes…
    REQUIRE (conditionPasses (data, 0, fillUp));
    // …and every PRE step behind it still reads `false`, because its PROB is 0.
    for (std::int64_t link = 1; link <= maxPreChainDepth; ++link)
    {
        INFO ("link " << link << " behind a PROB-0 anchor");
        REQUIRE (! conditionPasses (data, link, fillUp));
    }

    // The control: raise the anchor's PROB to 100 and the same links all fire.
    prob.values[0] = 100;
    const auto lifted = buildPatternSnapshot (state, 2);
    REQUIRE (lifted != nullptr);

    for (std::int64_t link = 1; link <= maxPreChainDepth; ++link)
    {
        INFO ("link " << link << " behind a PROB-100 anchor");
        REQUIRE (conditionPasses (lifted->patterns[0], link, fillUp));
    }
}

TEST_CASE ("sequencer/step-conditions: PRE is total on a cycle with no gated step at all", "[unit][determinism]")
{
    // `previousGatedOffset` is ALL-ZERO for an all-off GATE lane, which is D6's
    // other base case: there is no previous gated step anywhere, so the chain is
    // unanchored from the first hop. `conditionPasses` must still return — a
    // recursive formulation would not, and an implementation that treated 0 as a
    // valid hop would walk to `stepIndex - 0` forever.
    PatternSetState state = defaultedState (16, 1, false); // GATE entirely off
    auto& pattern = state.patterns[0];

    LaneState& cond = laneOf (pattern, LaneId::cond);
    cond.length = 1;
    cond.values[0] = static_cast<std::int16_t> (TrigCondition::pre);

    const auto preSnapshot = buildPatternSnapshot (state, 1);
    REQUIRE (preSnapshot != nullptr);
    const PatternData& preData = preSnapshot->patterns[0];

    // The table's base case, stated directly.
    REQUIRE (preData.gatePulsesPerLoop == 0);
    REQUIRE (PatternSnapshot::previousGatedOffsetAt (preData, 0) == 0);
    REQUIRE (PatternSnapshot::previousGatedOffsetAt (preData, 7) == 0);

    for (std::int64_t step = -20; step <= 20; ++step)
    {
        INFO ("unanchored PRE at step " << step);
        REQUIRE (! conditionPasses (preData, step, fillUp));
    }

    // `!PRE` inverts the base case ONCE (a single recorded link — the walk stops on
    // the very first hop), so it passes. That asymmetry is a consequence of the
    // base case being a value rather than "undefined", and it is pinned here so a
    // future change to the base case is visible as a test diff rather than as a
    // pattern that quietly starts firing.
    cond.values[0] = static_cast<std::int16_t> (TrigCondition::notPre);
    const auto notPreSnapshot = buildPatternSnapshot (state, 2);
    REQUIRE (notPreSnapshot != nullptr);

    for (std::int64_t step = -20; step <= 20; ++step)
    {
        INFO ("unanchored !PRE at step " << step);
        REQUIRE (conditionPasses (notPreSnapshot->patterns[0], step, fillUp));
    }
}

TEST_CASE ("sequencer/step-conditions: an all-PRE cycle is total and decays to silence", "[unit][determinism]")
{
    // THE NON-WELL-FOUNDED CASE, and the reason `maxPreChainDepth` exists at all.
    // Every gated step in the cycle carries `pre`, so the recurrence has no anchor:
    // "all true" and "all false" are both fixed points of it and a recursive
    // implementation would not terminate. The budget turns "undefined" into
    // "defined", and D6 picks `false`.
    const auto snapshot = truthTableSnapshot (ordinalPre, 0);
    REQUIRE (snapshot != nullptr);

    for (std::int64_t step = -20; step <= 40; ++step)
    {
        INFO ("all-PRE cycle at step " << step);
        REQUIRE (! conditionPasses (snapshot->patterns[0], step, fillUp));
    }
}

// ─────────────────────────────────────────────────────────────────────────────
// F. NEI / !NEI (user decision D7) and FILL / !FILL
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE ("sequencer/step-conditions: NEI flips at exactly MOD A 63 -> 64", "[unit][determinism]")
{
    // D7's v1 reading of §12.2's "neighbour mod lane's result": MOD A >= 64, i.e.
    // the mid-point of the lane's 0..127 range, so a lane at its default 0 reads as
    // !NEI. The THRESHOLD is the whole of the semantic, so it is asserted at the
    // two values either side of it and nowhere vaguer.
    STATIC_REQUIRE (neighbourModThreshold == 64);

    for (int modA = 0; modA <= 127; ++modA)
    {
        const auto neiSnapshot = truthTableSnapshot (ordinalNei, modA);
        const auto notNeiSnapshot = truthTableSnapshot (ordinalNotNei, modA);
        REQUIRE (neiSnapshot != nullptr);
        REQUIRE (notNeiSnapshot != nullptr);

        const bool expected = modA >= 64;
        INFO ("MOD A " << modA);
        REQUIRE (conditionPasses (neiSnapshot->patterns[0], 3, fillUp) == expected);
        REQUIRE (conditionPasses (notNeiSnapshot->patterns[0], 3, fillUp) == ! expected);
    }

    // The boundary, stated on its own so a failure reads as "the threshold moved".
    const auto at63 = truthTableSnapshot (ordinalNei, 63);
    const auto at64 = truthTableSnapshot (ordinalNei, 64);
    REQUIRE (! conditionPasses (at63->patterns[0], 0, fillUp));
    REQUIRE (conditionPasses (at64->patterns[0], 0, fillUp));
}

TEST_CASE ("sequencer/step-conditions: FILL/!FILL are driven by StepRuntime and nothing else", "[unit][determinism]")
{
    // The one input that is NOT a function of (snapshot, pattern, step). It arrives
    // by value on `StepRuntime` (the Phase 7.1 signature widening), so the SAME
    // snapshot at the SAME index must give opposite answers for the two values —
    // which is also what makes the sixth `step_purity` perturbation non-vacuous.
    const auto fillSnapshot = truthTableSnapshot (ordinalFill, 0);
    const auto notFillSnapshot = truthTableSnapshot (ordinalNotFill, 0);
    REQUIRE (fillSnapshot != nullptr);
    REQUIRE (notFillSnapshot != nullptr);

    for (std::int64_t step = -20; step <= 40; ++step)
    {
        INFO ("step " << step);
        REQUIRE (conditionPasses (fillSnapshot->patterns[0], step, fillDown));
        REQUIRE (! conditionPasses (fillSnapshot->patterns[0], step, fillUp));
        REQUIRE (! conditionPasses (notFillSnapshot->patterns[0], step, fillDown));
        REQUIRE (conditionPasses (notFillSnapshot->patterns[0], step, fillUp));
    }

    // FILL is orthogonal to every other condition: a `none` step ignores it.
    const auto noneSnapshot = truthTableSnapshot (ordinalNone, 0);
    REQUIRE (conditionPasses (noneSnapshot->patterns[0], 7, fillDown));
    REQUIRE (conditionPasses (noneSnapshot->patterns[0], 7, fillUp));
}

// ─────────────────────────────────────────────────────────────────────────────
// G. The `default:` arm — graceful degradation, not silence
// ─────────────────────────────────────────────────────────────────────────────

TEST_CASE ("sequencer/step-conditions: an out-of-enum COND ordinal degrades to `no condition`", "[unit][determinism]")
{
    // THE FORWARD-COMPATIBILITY ARM. The only way to reach it is a project saved by
    // a NEWER schema version and loaded by an older binary. Returning `false` would
    // SILENCE every step carrying the unknown condition — the user's pattern comes
    // back with holes in it and no error anywhere. Returning `true` degrades it to
    // "no condition": the step fires, which is recoverable by ear.
    // code-style.md's "graceful degradation, never crash", applied to a schema
    // mismatch.
    //
    // REACHING IT TAKES A POKE, AND THAT IS THE POINT. `buildPatternSnapshot` runs
    // every COND value through `clampLaneValue`, whose range is
    // [0, numTrigConditions - 1], so nothing out of enum can arrive through the
    // normal path. `PatternData` is trivially copyable, so the test copies a built
    // snapshot's pattern and writes the illegal ordinal straight into the copy —
    // which is exactly the shape "a datum that reached the RT path some other way"
    // takes.
    const auto snapshot = truthTableSnapshot (ordinalNone, 0);
    REQUIRE (snapshot != nullptr);

    // First: the clamp really does hold on the normal path.
    {
        PatternSetState state = defaultedState (16, 1, true);
        LaneState& cond = laneOf (state.patterns[0], LaneId::cond);
        cond.length = 1;
        cond.values[0] = 200;

        const auto clamped = buildPatternSnapshot (state, 1);
        REQUIRE (clamped != nullptr);
        REQUIRE (laneOf (clamped->patterns[0], LaneId::cond).values[0] == numTrigConditions - 1);
    }

    // Then: the arm itself, reached by poking a copy.
    for (const int illegal : { numTrigConditions, numTrigConditions + 1, 100, 32767 })
    {
        PatternData poked = snapshot->patterns[0];
        poked.lanes[static_cast<std::size_t> (LaneId::cond)].values[0] = static_cast<std::int16_t> (illegal);

        for (std::int64_t step = -5; step <= 20; ++step)
        {
            INFO ("illegal COND ordinal " << illegal << " at step " << step);
            REQUIRE (conditionPasses (poked, step, fillUp));
            REQUIRE (conditionPasses (poked, step, fillDown));
        }
    }

    // And the negative-ordinal side of the same argument (a corrupt blob, not a
    // newer schema) — `abCycleFor` rejects it and the same arm catches it.
    {
        PatternData poked = snapshot->patterns[0];
        poked.lanes[static_cast<std::size_t> (LaneId::cond)].values[0] = -7;
        REQUIRE (conditionPasses (poked, 4, fillUp));
    }
}
